"""Pierwsza pełna migracja

Revision ID: f9075dc91641
Revises: 
Create Date: 2024-12-03 19:54:06.906994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9075dc91641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correspondence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corDeadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('corComplited', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correspondence', schema=None) as batch_op:
        batch_op.drop_column('corComplited')
        batch_op.drop_column('corDeadline')

    # ### end Alembic commands ###
